import type { AppUser } from '@/types'

export const MOCK_USERS: AppUser[] = [
  {
    id: 'usr-001',
    name: 'Jordan Ellis',
    email: 'jordan.ellis@example.com',
    role: 'admin',
    status: 'active',
    avatarInitials: 'JE',
    avatarColor: '#6366f1',
    lastActive: '2026-02-13T14:30:00Z',
    createdAt: '2024-01-10T09:00:00Z',
    assignedCampaigns: ['ISI Sunrise Q1', 'NovaTech Product Launch'],
    permissions: ['view_reports','create_reports','export_data','manage_campaigns','manage_users','manage_settings','view_billing'],
    department: 'Sales',
    jobTitle: 'Senior Account Executive',
    phone: '+1 (555) 201-4400',
  },
  {
    id: 'usr-002',
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    role: 'campaign_manager',
    status: 'active',
    avatarInitials: 'PN',
    avatarColor: '#10b981',
    lastActive: '2026-02-13T11:15:00Z',
    createdAt: '2024-02-14T09:00:00Z',
    assignedCampaigns: ['ISI Sunrise Q1', 'NovaTech Product Launch', 'Healthcare Brand Awareness'],
    permissions: ['view_reports','create_reports','export_data','manage_campaigns'],
    department: 'Campaign Operations',
    jobTitle: 'Campaign Manager',
    phone: '+1 (555) 202-5511',
  },
  {
    id: 'usr-003',
    name: 'Marcus Webb',
    email: 'marcus.webb@example.com',
    role: 'analyst',
    status: 'active',
    avatarInitials: 'MW',
    avatarColor: '#f59e0b',
    lastActive: '2026-02-12T17:45:00Z',
    createdAt: '2024-03-01T09:00:00Z',
    assignedCampaigns: ['Apex Auto Brand Awareness'],
    permissions: ['view_reports','create_reports','export_data'],
    department: 'Analytics',
    jobTitle: 'Data Analyst',
    phone: '+1 (555) 203-6622',
  },
  {
    id: 'usr-004',
    name: 'Sofia Reyes',
    email: 'sofia.reyes@example.com',
    role: 'campaign_manager',
    status: 'active',
    avatarInitials: 'SR',
    avatarColor: '#ec4899',
    lastActive: '2026-02-13T09:00:00Z',
    createdAt: '2024-03-15T09:00:00Z',
    assignedCampaigns: ['Apex Auto Brand Awareness', 'ISI Sunrise Q1'],
    permissions: ['view_reports','create_reports','export_data','manage_campaigns'],
    department: 'Campaign Operations',
    jobTitle: 'Senior Campaign Manager',
    phone: '+1 (555) 204-7733',
  },
  {
    id: 'usr-005',
    name: 'Daniel Park',
    email: 'daniel.park@example.com',
    role: 'analyst',
    status: 'active',
    avatarInitials: 'DP',
    avatarColor: '#8b5cf6',
    lastActive: '2026-02-11T16:20:00Z',
    createdAt: '2024-04-01T09:00:00Z',
    assignedCampaigns: ['Healthcare Brand Awareness'],
    permissions: ['view_reports','create_reports','export_data'],
    department: 'Analytics',
    jobTitle: 'Analytics Engineer',
  },
  {
    id: 'usr-006',
    name: 'Rachel Kim',
    email: 'rachel.kim@example.com',
    role: 'viewer',
    status: 'active',
    avatarInitials: 'RK',
    avatarColor: '#06b6d4',
    lastActive: '2026-02-10T10:05:00Z',
    createdAt: '2024-05-20T09:00:00Z',
    assignedCampaigns: ['ISI Sunrise Q1'],
    permissions: ['view_reports'],
    department: 'Finance',
    jobTitle: 'Finance Business Partner',
  },
  {
    id: 'usr-007',
    name: 'Tom Nguyen',
    email: 'tom.nguyen@example.com',
    role: 'viewer',
    status: 'invited',
    avatarInitials: 'TN',
    avatarColor: '#14b8a6',
    lastActive: '2026-02-08T08:30:00Z',
    createdAt: '2026-02-08T08:00:00Z',
    assignedCampaigns: [],
    permissions: ['view_reports'],
    department: 'Marketing',
    jobTitle: 'Marketing Coordinator',
  },
  {
    id: 'usr-008',
    name: 'Aisha Okonkwo',
    email: 'aisha.okonkwo@example.com',
    role: 'analyst',
    status: 'active',
    avatarInitials: 'AO',
    avatarColor: '#f97316',
    lastActive: '2026-02-13T13:00:00Z',
    createdAt: '2024-06-10T09:00:00Z',
    assignedCampaigns: ['NovaTech Product Launch', 'Apex Auto Brand Awareness'],
    permissions: ['view_reports','create_reports','export_data'],
    department: 'Analytics',
    jobTitle: 'Senior Data Analyst',
    phone: '+1 (555) 208-1144',
  },
  {
    id: 'usr-009',
    name: 'Chris Lawson',
    email: 'chris.lawson@example.com',
    role: 'admin',
    status: 'active',
    avatarInitials: 'CL',
    avatarColor: '#64748b',
    lastActive: '2026-02-13T07:55:00Z',
    createdAt: '2024-01-05T09:00:00Z',
    assignedCampaigns: ['ISI Sunrise Q1', 'Healthcare Brand Awareness', 'NovaTech Product Launch', 'Apex Auto Brand Awareness'],
    permissions: ['view_reports','create_reports','export_data','manage_campaigns','manage_users','manage_settings','view_billing'],
    department: 'Engineering',
    jobTitle: 'Platform Administrator',
    phone: '+1 (555) 209-2255',
  },
  {
    id: 'usr-010',
    name: 'Mei Zhang',
    email: 'mei.zhang@example.com',
    role: 'campaign_manager',
    status: 'inactive',
    avatarInitials: 'MZ',
    avatarColor: '#a78bfa',
    lastActive: '2025-12-20T15:00:00Z',
    createdAt: '2024-07-01T09:00:00Z',
    assignedCampaigns: [],
    permissions: ['view_reports','create_reports','manage_campaigns'],
    department: 'Campaign Operations',
    jobTitle: 'Campaign Specialist',
  },
  {
    id: 'usr-011',
    name: 'Ben Okafor',
    email: 'ben.okafor@example.com',
    role: 'viewer',
    status: 'suspended',
    avatarInitials: 'BO',
    avatarColor: '#ef4444',
    lastActive: '2026-01-15T09:00:00Z',
    createdAt: '2024-08-12T09:00:00Z',
    assignedCampaigns: [],
    permissions: [],
    department: 'Legal',
    jobTitle: 'Legal Counsel',
  },
  {
    id: 'usr-012',
    name: 'Laura Simmons',
    email: 'laura.simmons@example.com',
    role: 'analyst',
    status: 'invited',
    avatarInitials: 'LS',
    avatarColor: '#0ea5e9',
    lastActive: '2026-02-12T00:00:00Z',
    createdAt: '2026-02-12T10:00:00Z',
    assignedCampaigns: [],
    permissions: ['view_reports','create_reports'],
    department: 'Analytics',
    jobTitle: 'Junior Analyst',
  },
]
